# Generated by Django 4.2 on 2023-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_created=True)),
                ("username", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=255)),
            ],
        ),
    ]
